kind: Deployment
apiVersion: apps/v1
metadata:
  name: apm-eureka
  namespace: kubesphere-sample-dev
  labels:
    app: apm-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-eureka
  template:
    metadata:
      name: apm-eureka
      labels:
        app: apm-eureka
    spec:
      volumes:
        - name: skywalking-agent
          emptyDir: {}
      initContainers:
        - name: sidecar
          image: 'apache/skywalking-java-agent:9.0.0-alpine'
          command:
            - cp
            - '-r'
            - /skywalking/agent
            - /agent
          resources: {}
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
      containers:
        - name: apm-eureka
          image: 'evanxuhe/apm-eureka:6.1.0'
          ports:
            - name: http
              containerPort: 8761
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: '-javaagent:/skywalking/agent/skywalking-agent.jar'
            - name: SW_AGENT_NAME
              value: apm-eureka
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: 'skw-oap.kubesphere-sample-dev.svc:11800'
          resources: {}
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking
