kind: Deployment
apiVersion: apps/v1
metadata:
  name: apm-item
  namespace: kubesphere-sample-dev
  labels:
    app: apm-item
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-item
  template:
    metadata:
      name: apm-item
      labels:
        app: apm-item
    spec:
      volumes:
        - name: skywalking-agent
          emptyDir: {}
      initContainers:
        - name: sidecar
          image: 'apache/skywalking-java-agent:9.0.0-alpine'
          command:
            - cp
            - '-r'
            - /skywalking/agent
            - /agent
          resources: {}
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
      containers:
        - name: apm-item
          image: 'evanxuhe/apm-item:6.1.0'
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: '-javaagent:/skywalking/agent/skywalking-agent.jar'
            - name: SW_AGENT_NAME
              value: apm-item
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: 'skw-oap.kubesphere-sample-dev.svc:11800'
            - name: EUREKA_HOSTNAME
              value: apm-eureka
            - name: EUREKA_PORT
              value: '8761'
          resources: {}
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking
