kind: ConfigMap
apiVersion: v1
metadata:
  name: es
  namespace: kubesphere-sample-dev
data:
  elasticsearch.yml: |2-
      cluster.name: my-cluster
      node.name: node-1
      node.max_local_storage_nodes: 3
      network.host: 0.0.0.0
      http.port: 9200
      discovery.seed_hosts: ["127.0.0.1", "[::1]"]
      cluster.initial_master_nodes: ["node-1"]
      http.cors.enabled: true
      http.cors.allow-origin: /.*/
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.security.transport.ssl.enabled: true
      
