kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es
  namespace: kubesphere-sample-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local
  volumeMode: Filesystem
