kind: Service
apiVersion: v1
metadata:
  name: es
  namespace: kubesphere-sample-dev
  labels:
    app: es
    version: v1
spec:
  ports:
    - name: tcp-9200
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: tcp-9300
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: es
  type: ClusterIP
  sessionAffinity: None
