kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oap-pv
  namespace: kubesphere-sample-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local
  volumeMode: Filesystem
